name: ci

on:
  pull_request:
    paths:
      - 'src/**'
      - package.json
      - yarn.lock
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: yarn

      - name: Build
        run: yarn build
